---
- import_tasks: ubuntu20.yml
  when: ansible_os_family == "Ubuntu"  or
     ansible_distribution_major_version >= 8 and ansible_os_family == "RedHat"
  ignore_errors: true
- import_tasks: generic_install.yml
  when: ansible_os_family != "Ubuntu"

- name: Generate config
  template:
    src: cli.ini.j2
    dest: /etc/letsencrypt/cli.ini
    mode: 0644

- name: Get cert
  command: certbot certonly -c /etc/letsencrypt/cli.ini
  register: certbot
  changed_when: "certbot.rc != 0"

- name: Add cron
  cron:
    name: "renew cert"
    minute: "52"
    hour: "0,12"
    user: root
    job: "certbot renew -q -c /etc/letsencrypt/cli.ini"
